version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=river_of_books
    ports:
      - 6500:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# on localhost:8080 will run adminer - there you can under PostgreSQL on Server: db under Username: postgres and Password: example explore db